# Generated by Django 3.1.5 on 2021-01-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0007_image_if_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='if_main',
            new_name='is_main',
        ),
    ]
