# Generated by Django 3.1.5 on 2021-01-14 20:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_image_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=(640, 480), upload_to='static/images'),
        ),
    ]
